language: java

install: 
  # install C++
  - sudo apt-get install g++
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  verbose: true
  keep-history: true
# aggiunto ci skip così posso fare commit sul master
  project-name: asmeta2cpp results [ci skip]
# current dir to deploy to ghpages
# local-dir: results
# attenzione sul master direttamente può fare danni crea ricorsione
# target-branch: gh-pages
  target-branch: master
  on:
    branch: master
